# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wucluster}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip (flip) Kromer"]
  s.date = %q{2010-03-04}
  s.description = %q{Persistent mapping of volume and snapshot to cluster, node and mount point}
  s.email = %q{flip@infochimps.org}
  s.executables = ["console_helper.rb", "ec2-putaway-volumes.rb", "wucluster"]
  s.extra_rdoc_files = [
    "LICENSE.textile",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.textile",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/console_helper.rb",
     "bin/ec2-putaway-volumes.rb",
     "bin/wucluster",
     "lib/AWS/EC2/overrides.rb",
     "lib/wucluster.rb",
     "lib/wucluster/cluster.rb",
     "lib/wucluster/cluster/catalog.rb",
     "lib/wucluster/cluster/components.rb",
     "lib/wucluster/cluster/layout.rb",
     "lib/wucluster/dependency_graph.rb",
     "lib/wucluster/ec2_proxy.rb",
     "lib/wucluster/exceptions.rb",
     "lib/wucluster/extensions.rb",
     "lib/wucluster/extensions/hash.rb",
     "lib/wucluster/instance.rb",
     "lib/wucluster/instance/components.rb",
     "lib/wucluster/instance/ec2.rb",
     "lib/wucluster/keypair.rb",
     "lib/wucluster/mock/dependency_graph_sim.rb",
     "lib/wucluster/security_group.rb",
     "lib/wucluster/snapshot.rb",
     "lib/wucluster/volume.rb",
     "lib/wucluster/volume/components.rb",
     "lib/wucluster/volume/ec2.rb",
     "notes/states.fa",
     "old/mock.rb",
     "old/mock_cluster_mount.rb",
     "old/mook.rb",
     "old/state_machine.rb",
     "spec/blueprints.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/wucluster/cluster_spec.rb",
     "spec/wucluster/mount_spec.rb",
     "spec/wucluster/volume_spec.rb",
     "spec/wucluster_spec.rb",
     "wucluster.gemspec"
  ]
  s.homepage = %q{http://github.com/mrflip/wucluster}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simple EBS volume management for hadoop clusters}
  s.test_files = [
    "spec/blueprints.rb",
     "spec/spec_helper.rb",
     "spec/wucluster/cluster_spec.rb",
     "spec/wucluster/mount_spec.rb",
     "spec/wucluster/volume_spec.rb",
     "spec/wucluster_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amazon-ec2>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<amazon-ec2>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<amazon-ec2>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

